server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xhub_booking
    username: root
    password: ndyudev227
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # không tự động tạo bảng nữa
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
