server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xhub_booking
    username: root
    password: ndyudev227
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  swagger-ui:
    enabled: false
